version: 2
updates:
- package-ecosystem: npm
  directory: "/interfaces/HO-Portal"
  schedule:
    interval: weekly
  open-pull-requests-limit: 3
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: "@angular/*"
    versions: ["^8", "^0.800.x"]
  - dependency-name: "@angular-devkit/*"
    versions: ["^0.800.x"]
  - dependency-name: "@types/node"
    versions: ["^11"]
  - dependency-name: tslint
    versions: ["^6"]
  - dependency-name: codelyzer
    versions: ["^6"]
  - dependency-name: core-js
    versions: ["^3"]
  - dependency-name: tslib
    versions: ["^2"]
  - dependency-name: "@ngx-translate/http-loader"
    versions: ["^5"]
  - dependency-name: ngx-translate-lint
    versions: ["^1.4.x", "^1.6.0"]

- package-ecosystem: npm
  directory: "/interfaces/AW-App"
  schedule:
    interval: weekly
  open-pull-requests-limit: 3
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: "@angular/*"
    versions: ["^8", "^0.800.x"]
  - dependency-name: "@angular-devkit/*"
    versions: ["^0.800.x"]
  - dependency-name: "@ionic/storage"
    versions: ["^2.3.0"]
  - dependency-name: "@types/node"
    versions: ["^11"]
  - dependency-name: tslint
    versions: ["^6"]
  - dependency-name: codelyzer
    versions: ["^6"]
  - dependency-name: core-js
    versions: ["^3"]
  - dependency-name: tslib
    versions: ["^2"]
  - dependency-name: "@ngx-translate/http-loader"
    versions: ["^5"]
  - dependency-name: ngx-translate-lint
    versions: ["^1.4.x", "^1.6.0"]

- package-ecosystem: npm
  directory: "/interfaces/PA-App"
  schedule:
    interval: weekly
  open-pull-requests-limit: 3
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: "@angular/*"
    versions: ["^8", "^0.800.x"]
  - dependency-name: "@angular-devkit/*"
    versions: ["^0.800.x"]
  - dependency-name: "@ionic/storage"
    versions: ["^2.3.0"]
  - dependency-name: "@types/node"
    versions: ["^11"]
  - dependency-name: tslint
    versions: ["^6"]
  - dependency-name: codelyzer
    versions: ["^6"]
  - dependency-name: core-js
    versions: ["^3"]
  - dependency-name: tslib
    versions: ["^2"]
  - dependency-name: "@ngx-translate/http-loader"
    versions: ["^5"]
  - dependency-name: ngx-translate-lint
    versions: ["^1.4.x", "^1.6.0"]
  - dependency-name: angularx-qrcode
    versions: ["^2.1.x"]

- package-ecosystem: npm
  directory: "/interfaces/Referral-App"
  schedule:
    interval: weekly
  open-pull-requests-limit: 3
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: "@angular/*"
    versions: ["^8", "^0.800.x"]
  - dependency-name: "@angular-devkit/*"
    versions: ["^0.800.x"]
  - dependency-name: "@ionic/storage"
    versions: ["^2.3.0"]
  - dependency-name: "@types/node"
    versions: ["^11"]
  - dependency-name: tslint
    versions: ["^6"]
  - dependency-name: codelyzer
    versions: ["^6"]
  - dependency-name: core-js
    versions: ["^3"]
  - dependency-name: tslib
    versions: ["^2"]
  - dependency-name: "@ngx-translate/http-loader"
    versions: ["^5"]
