# See: https://docs.microsoft.com/azure/devops/pipelines/yaml-schema
# See: https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - master
      - release/*
  paths:
    include:
      - 'services/PA-accounts-service/*'
pr:
  branches:
    include:
      - master
  paths:
    include:
      - 'services/PA-accounts-service/*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'

  - script: npm ci
    displayName: Install
    workingDirectory: services/PA-accounts-service/

  - script: npm test
    displayName: Tests
    workingDirectory: services/PA-accounts-service/
    env:
      SECRETS_PA_ACCOUNTS_SERVICE_SECRET: test
