version: '3.7'

services:
  indypool:
    build:
      context: tykn-ssi-services
      dockerfile: indy-pool.dockerfile
      args:
        pool_ip: '11.0.0.2'
    init: true
    container_name: tykn_indy_pool
    healthcheck:
      test: "exit 0"
    ports:
      - "9701:9701"
      - "9702:9702"
      - "9703:9703"
      - "9704:9704"
      - "9705:9705"
      - "9706:9706"
      - "9707:9707"
      - "9708:9708"
    networks:
      pool_network:
        ipv4_address: 11.0.0.2
    restart: unless-stopped
  tyknims:
    build:
      context: tykn-ssi-services/TyknIMS
      dockerfile: Dockerfile
    init: true
    container_name: tyknims
    volumes:
      - "./tykn-ssi-services/TyknIMS/wallet-volume:/tmp/.indy_client/wallet"
      - "./logs-volume:/var/log/tyknims"
    ports:
      - "50001:50001"
    networks:
      pool_network:
        ipv4_address: 11.0.0.3
    healthcheck:
      test: "exit 0"
    depends_on:
      - indypool
    links:
      - indypool
    restart: unless-stopped
  orgims:
    build:
      context: tykn-ssi-services/OrgIMS
      dockerfile: Dockerfile
      args:
        - CONFIG=config.json
    init: true
    container_name: orgims
    volumes:
      - "./tykn-ssi-services/OrgIMS/wallet-volume:/tmp/wallet"
      - "./logs-volume:/var/log/orgims"
    ports:
      - "50002:50002"
    healthcheck:
      test: "exit 0"
    restart: unless-stopped
    networks:
      pool_network:
        ipv4_address: 11.0.0.4
    depends_on:
      - indypool
      - tyknims
    links:
      - indypool
      - tyknims
    restart: unless-stopped
  userims:
    build:
      context: tykn-ssi-services/UserIMS
      dockerfile: Dockerfile
    init: true
    container_name: userims
    volumes:
      - "./tykn-ssi-services/UserIMS/wallet-volume:/tmp/.indy_client"
      - "./logs-volume:/var/log/userims"
    healthcheck:
      test: "exit 0"
    restart: on-failure
    ports:
      - "50003:50003"
    networks:
      pool_network:
        ipv4_address: 11.0.0.5
    depends_on:
      - indypool
      - tyknims
    links:
      - indypool
    restart: unless-stopped
  121db:
    image: "postgres:9.6"
    init: true
    container_name: 121db
    environment:
      - POSTGRES_USER=global121
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=global121
    volumes:
      - "./postgresql.conf:/etc/postgresql.conf"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "5438:5432"
    networks:
      pool_network:
        ipv4_address: 11.0.0.6
    restart: unless-stopped
  121-service:
    build:
      context: 121-service
      dockerfile: Dockerfile
    init: true
    container_name: 121-service
    environment:
      - EXTERNAL_121_SERVICE_URL=${EXTERNAL_121_SERVICE_URL}
      - RESET_SECRET=${RESET_SECRET}
      - PORT_121_SERVICE=${PORT_121_SERVICE}
      - SUBDOMAIN_121_SERVICE=${SUBDOMAIN_121_SERVICE}
      - URL_PA_ACCOUNTS_SERVICE_API=${URL_PA_ACCOUNTS_SERVICE_API}
      - NODE_ENV=${NODE_ENV_121}
    volumes:
      - "./121-service:/home/121/services/121-service"
    ports:
      - "${PORT_121_SERVICE}:${PORT_121_SERVICE}"
    stdin_open: true
    tty: true
    networks:
      pool_network:
        ipv4_address: ${IPV4_121_SERVICE}
    depends_on:
      - 121db
    restart: on-failure
  PA-accounts-service:
    build:
      context: PA-accounts-service
      dockerfile: Dockerfile
    image: pa-accounts-node
    init: true
    container_name: PA-accounts-service
    environment:
      - WALLET_PASSWORD_ENCRYPTION_KEY=${WALLET_PASSWORD_ENCRYPTION_KEY}
      - PORT_PA_ACCOUNTS_SERVICE=${PORT_PA_ACCOUNTS_SERVICE}
      - SUBDOMAIN_PA_ACCOUNTS_SERVICE=${SUBDOMAIN_PA_ACCOUNTS_SERVICE}
      - URL_121_SERVICE_API=${URL_121_SERVICE_API}
      - NODE_ENV=${NODE_ENV_PA}
    volumes:
      - "./PA-accounts-service:/home/121/services/PA-accounts-service"
    ports:
      - "${PORT_PA_ACCOUNTS_SERVICE}:${PORT_PA_ACCOUNTS_SERVICE}"
    stdin_open: true
    tty: true
    networks:
      pool_network:
        ipv4_address: ${IPV4_PA_ACCOUNTS_SERVICE}
    depends_on:
      - 121db
    restart: on-failure

networks:
  pool_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 11.0.0.0/24
