version: '3.7'

# The settings from this file will override the values from `docker-compose.yml`
# When run via:
#     docker-compose -f docker-compose.yml -f docker-compose.development.yml

# For use on macOS:
# See: https://www.docker.com/blog/user-guided-caching-in-docker-for-mac/
# To speed up the start-up process, use: ':cached' flag on volume definitions

# For debugging:
#
# Make the service boot and wait:
#     command: "tail -f /dev/null"
#

services:
  121-service:
    build:
      target: development
    volumes:
      - '121_service_node_modules:/home/node/app/node_modules'
      - './121-service:/home/node/app'

  PA-accounts-service:
    build:
      target: development
    volumes:
      - 'pa_accounts_node_modules:/home/node/app/node_modules'
      - './PA-accounts-service:/home/node/app'
    # When the file-watcher isn't necessary, you can override the start-command here:
    # command: 'npm start'

volumes:
  121_service_node_modules:
  pa_accounts_node_modules:
