version: '3.7'

# The settings from this file will override the values from `docker-compose.yml`
# When run via:
#     docker-compose -f docker-compose.yml -f docker-compose.development.yml

# For debugging:
#
# Make the service boot and wait:
#     command: "tail -f /dev/null"
#

services:
  121-service:
    # For use on macOS: to speed up the start-up process, uncomment:
    # volumes: ["./121-service:/home/node/app:cached"]
    command: "npm run start:dev"

  PA-accounts-service:
    # For use on macOS: to speed up the start-up process, uncomment:
    # volumes: ["./PA-accounts-service:/home/node/app:cached"]
    command: "npm run start:dev"
