version: '3.7'

services:
  121db:
    image: 'postgres:9.6'
    init: true
    container_name: 121db
    environment:
      - POSTGRES_USER=global121
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=global121
    volumes:
      - './postgresql.conf:/etc/postgresql.conf'
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
    ports:
      - '5438:5432'
    networks:
      pool_network:
        ipv4_address: 11.0.0.6
    restart: unless-stopped
  121-service:
    build:
      context: 121-service
    init: true
    container_name: 121-service
    env_file:
      - .env
    environment:
      - GLOBAL_121_VERSION
    ports:
      - '${PORT_121_SERVICE}:${PORT_121_SERVICE}'
    stdin_open: true
    tty: true
    networks:
      pool_network:
        ipv4_address: ${IPV4_121_SERVICE}
    depends_on:
      - 121db
    restart: on-failure
  PA-accounts-service:
    build:
      context: PA-accounts-service
    image: services_pa-accounts-service
    init: true
    container_name: pa-accounts-service
    env_file:
      - .env
    environment:
      - GLOBAL_121_VERSION
    ports:
      - '${PORT_PA_ACCOUNTS_SERVICE}:${PORT_PA_ACCOUNTS_SERVICE}'
    stdin_open: true
    tty: true
    networks:
      pool_network:
        ipv4_address: ${IPV4_PA_ACCOUNTS_SERVICE}
    depends_on:
      - 121db
    restart: on-failure

networks:
  pool_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 11.0.0.0/24
